name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Update CA certificates
      run: sudo apt-get update && sudo apt-get install -y ca-certificates

    - name: Install Tor
      run: sudo apt-get install -y tor

    - name: Install procps for pkill
      run: sudo apt-get install -y procps

    - name: Stop Tor service if running
      run: sudo service tor stop || true

    - name: Kill any existing Tor processes
      run: sudo pkill -f tor || true

    - name: Start Tor in the background
      run: nohup tor &

    - name: Install dependencies
      run: go mod download

    - name: Tidy Go modules
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run linter
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Run static analysis
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...